scala_library(
    sources = globs("*.scala"),
    dependencies = [
        "src/main/scala/apiparser/util:util",
        "src/main/scala/apiparser/common:common",
        "src/main/scala/apiparser/model:model",
        "src/main/scala/apiparser/model/config:config",
        "src/main/scala/apiparser/model/AcsMatch:AcsMatch",
        "src/main/scala/apiparser/model/transformed:transformed",
        "src/main/scala/apiparser/processor:processor",
        "3rdparty/jvm:externalLib"
    ],
)
