scala_library(
    sources = globs("*.scala"),
    dependencies = [
        "src/main/scala/apiparser/model:model",
        "src/main/scala/apiparser/model/champion:champion",
        "src/main/scala/apiparser/model/AcsMatch:AcsMatch",
        "src/main/scala/apiparser/model/config:config",
        "src/main/resources:resources",
        "3rdparty/jvm:externalLib"
    ],
)
