scala_library(
    sources = globs("*.scala"),
    dependencies = [
        "src/main/scala/apiparser/util:util",
        "src/main/scala/apiparser/model:model",
        "src/main/scala/apiparser/model/AcsMatch:AcsMatch",
        "3rdparty/jvm:externalLib",
        "src/protobuf/matches:matches"
    ],
)
